//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterSwimming.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceDate
    {
        public int Id { get; set; }
        public int ClientServiceId { get; set; }
        public System.DateTime DateOfLesson { get; set; }
    
        public virtual ClientService ClientService { get; set; }
    }
}
